version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: "@web/dev-server"
    versions:
    - 0.1.14
  - dependency-name: "@vaadin/vaadin"
    versions:
    - 19.0.5
  - dependency-name: "@web/test-runner"
    versions:
    - 0.12.20
  - dependency-name: rollup
    versions:
    - 2.41.4
    - 2.41.5
    - 2.42.0
